"""Referee brief-stage check, post4: does the publication floor (a `yes` cell publishes only if
yes >= 15) manufacture a success–growth correlation under the null, and does the pp outcome's
'unweighted' estimator have an informative effective N?  Uses the real November/February node
sizes and NO real success data: true success is drawn independent of share.

    python posts/post4/notes/rederivation/null_floor_simulation.py
"""
import numpy as np, pandas as pd, os

C = 'data/cache'
nov = pd.read_parquet(f'{C}/release_2026_01_15/data/intermediate/aei_raw_claude_ai_2025-11-13_to_2025-11-20.parquet')
feb = pd.read_parquet(f'{C}/release_2026_03_24/data/aei_raw_claude_ai_2026-02-05_to_2026-02-12.parquet')
OUT = os.path.join(os.path.dirname(__file__), 'null_floor_simulation.txt')
L = []
def P(*a):
    s = ' '.join(str(x) for x in a); L.append(s); print(s)

def counts(d):
    g = d[(d.geography == 'global') & (d.facet == 'onet_task') & (d.level.astype(str) == '0') & (d.variable == 'onet_task_count')]
    s = g.set_index(g.cluster_name.str.strip().str.lower()).value
    return s.drop(index=[i for i in ('none', 'not_classified') if i in s.index])

nN, nF = counts(nov), counts(feb)
# the population of tasks: every task seen in either wave; true intensity = mean of the two
# (a task absent in one wave gets the other wave's count, so churn is generated by noise + floor)
allt = nN.index.union(nF.index)
lam = pd.concat([nN.reindex(allt), nF.reindex(allt)], axis=1).mean(axis=1)
lam = lam.values.astype(float)
K = len(lam)
P(f'population tasks={K}; real Nov named nodes={len(nN)}, Feb={len(nF)}, matched={len(nN.index.intersection(nF.index))}')

rng = np.random.default_rng(20260916)
def one(rule_min=15, outcome='log', control=True, R=400, p_mean=0.67, p_sd=0.15):
    rs = []
    a, b = p_mean * (p_mean*(1-p_mean)/p_sd**2 - 1), (1-p_mean) * (p_mean*(1-p_mean)/p_sd**2 - 1)
    for _ in range(R):
        p = rng.beta(a, b, K)                       # true success, independent of share
        n1 = rng.poisson(lam); n2 = rng.poisson(lam * 1e6/999875)
        y = rng.binomial(n1, p)
        pub = (n1 >= 15) & (n2 >= 15) & (y >= 15) & (n1 >= rule_min)   # in both waves, yes cell published, size rule
        s1 = 100*n1/999875; s2 = 100*n2/1e6
        yp = 100*y/np.maximum(n1, 1)
        if outcome == 'log':
            dy = np.log(s2[pub]/s1[pub])
        else:
            dy = s2[pub]-s1[pub]
        x = yp[pub]
        if control:
            Z = np.column_stack([np.ones(pub.sum()), np.log(s1[pub])])
            dy = dy - Z @ np.linalg.lstsq(Z, dy, rcond=None)[0]
            x = x - Z @ np.linalg.lstsq(Z, x, rcond=None)[0]
        rs.append(np.corrcoef(x, dy)[0, 1])
    rs = np.array(rs)
    return rs.mean(), rs.std(), int(pub.sum())

P('== null correlation of published yes_pct with share growth (true success independent of share)')
P('   rule = minimum November node size; control = partial on log November share')
for outcome in ('log', 'pp'):
    for control in (False, True):
        for rule in (15, 30, 50, 100):
            m, s, n = one(rule, outcome, control)
            P(f'  outcome={outcome:3s} control={str(control):5s} n_nov>={rule:3d}: N≈{n:5d}  null r mean={m:+.4f} sd={s:.4f}')

P('== published yes_pct by node size under the null (one draw), to compare with the real gradient')
p = rng.beta(0.67*(0.67*0.33/0.15**2-1), 0.33*(0.67*0.33/0.15**2-1), K)
n1 = rng.poisson(lam); y = rng.binomial(n1, p); pub = (n1 >= 15) & (y >= 15)
yp = 100*y/np.maximum(n1, 1)
for lo, hi in [(15, 21), (21, 31), (31, 51), (51, 101), (101, 501), (501, 10**7)]:
    m = pub & (n1 >= lo) & (n1 < hi)
    P(f'  n in [{lo},{hi-1}]: published N={m.sum():4d} mean published yes_pct={yp[m].mean():.2f}  (true mean p among them={100*p[m].mean():.2f})')

P('== effective N of a pp-change regression: Kish N with weights s^2 (pp change scales with level)')
nb = nN.reindex(nN.index.intersection(nF.index)).values
for w, lab in [(nb, 's'), (nb**2, 's^2')]:
    P(f'  weights {lab:4s}: Kish N_eff = {w.sum()**2/(w**2).sum():.1f}')

with open(OUT, 'w') as f: f.write('\n'.join(L) + '\n')
P(f'-- written {OUT}')
