#!/usr/bin/env python3
"""Generate the v1 audit CSV deliverables from the audited evidence.

Writes, next to this script's parent directory:
  source-register.csv   proposed register rows (existing IDs preserved, new IDs marked)
  coverage.csv          entity-level coverage, countries separated from aggregates
  search-log.csv        this audit's dated searches and provider checks
  permitted-cells.csv   the exact published cells proposed for display in v1

Run from anywhere:  python3 build_tables.py
Validation: run check_outputs.py afterwards.
"""

import csv
import pathlib

OUT = pathlib.Path(__file__).resolve().parent.parent

REGISTER_FIELDS = [
    "indicator_id", "question", "construct", "source", "source_url", "sample_family",
    "population", "geography", "fieldwork_or_reference", "unit", "denominator",
    "gender_measure", "ai_definition", "comparison_group", "verification_status",
    "audit_record", "access_status", "redistribution_status", "uncertainty",
    "missingness_or_selection", "next_check", "new_check_this_setup",
    "joint_fields", "design_weights_precision", "evidence_level", "id_status",
    "lead_slot",
]

A = "evidence/v1-audit-2026-10-01"

REGISTER = [
    dict(
        indicator_id="EU_USE",
        question="Who uses generative AI?", construct="participation",
        source="Eurostat isoc_ai_iaiu",
        source_url="https://ec.europa.eu/eurostat/databrowser/view/isoc_ai_iaiu/default/table?lang=en",
        sample_family="EU_ICT_2025",
        population="Individuals aged 16-74 in survey scope",
        geography="2 aggregates (EU27_2020, EA) plus 35 countries/territories; Iceland absent",
        fieldwork_or_reference="2025 only; reference period generally Q1 of the reference year; previous three months; national fieldwork timing varies",
        unit="people; indic_is I_IUAI",
        denominator="unit code is the denominator: PC_IND all individuals or PC_IND_IU3 recent internet users; B5 asked only of recent internet users",
        gender_measure="no sex dimension; sex is an ind_type prefix (M_Y16_74 / F_Y16_74); 2025 model questionnaire item H2 Sex has Male and Female only",
        ai_definition="generative AI: tools such as ChatGPT, Copilot, Gemini, LLaMA, Midjourney, DALL-E creating text, images, code or video (item B5)",
        comparison_group="within Eurostat same-year definitions",
        verification_status="file-verified 2026-10-01 (pilot); re-downloaded 2026-10-01 in this audit, same SHA-256 7f668f7b...96ab; 37 geo codes re-counted",
        audit_record=f"{A}/pilot-corrections.md; evidence/pilot-2026-10-01/eurostat-profile.md",
        access_status="open bulk download; no registration; DOI 10.2908/ISOC_AI_IAIU",
        redistribution_status="Eurostat notice: commercial and non-commercial reuse with source acknowledged, modification disclosed; commercial-reuse exclusion for non-EU/EFTA/candidate geographies must be checked per country (BA, XK unresolved)",
        uncertainty="no published standard error for any generative-AI rate or male-female difference (ESMS 13.2 covers e-commerce only); national precision publications not audited; only flag is u",
        missingness_or_selection="of 39006 cells 32307 unflagged, 3503 flagged u, 3196 unavailable; headline M/F complete and unflagged in all 37 geographies; missing is not zero",
        next_check="read country-specific comparability notes (CIRCABC route blocked 2026-10-01) before any country comparison; treat a 2026 wave as a new edition with a break check",
        new_check_this_setup="false",
        joint_fields="sex crossed with age and education only; never with occupation, activity status, urbanisation or country of birth",
        design_weights_precision="harmonised EU model questionnaire 2025 implemented nationally; about 172k households and 330k individuals surveyed in the EU in 2025 (ESMS 16); no design effect or standard error published",
        evidence_level="file-verified-aggregate", id_status="existing", lead_slot="",
    ),
    dict(
        indicator_id="EU_PURPOSE",
        question="How does use differ by context?", construct="patterns",
        source="Eurostat isoc_ai_iaiu",
        source_url="https://ec.europa.eu/eurostat/databrowser/view/isoc_ai_iaiu/default/table?lang=en",
        sample_family="EU_ICT_2025", population="Individuals aged 16-74",
        geography="same table and geography as EU_USE",
        fieldwork_or_reference="2025 only; previous three months",
        unit="people; indic_is I_IUAIPR / I_IUAIWP / I_IUAIFE",
        denominator="PC_IND, PC_IND_IU3 or PC_IND_IUAI; must be stated; item B6 is multiple response so purposes do not sum to 100",
        gender_measure="same ind_type sex codes as EU_USE; H2 Sex Male/Female only",
        ai_definition="generative AI as in EU_USE", comparison_group="within purpose and stated denominator",
        verification_status="file-verified 2026-10-01 (pilot); denominator arithmetic reproduced by the coordinator review; not re-run here",
        audit_record=f"{A}/pilot-corrections.md; evidence/pilot-2026-10-01/eurostat-profile.md",
        access_status="open bulk download; DOI 10.2908/ISOC_AI_IAIU",
        redistribution_status="as EU_USE",
        uncertainty="no published standard errors or gap variances; u flag only",
        missingness_or_selection="multiple purposes per respondent; the work-purpose denominator is not restricted to workers; suppression increases in fine ind_type cells",
        next_check="keep sample family EU_ICT_2025 with EU_USE and EU_NONUSE; never count as independent evidence",
        new_check_this_setup="false",
        joint_fields="as EU_USE",
        design_weights_precision="as EU_USE",
        evidence_level="file-verified-aggregate", id_status="existing", lead_slot="",
    ),
    dict(
        indicator_id="EU_NONUSE",
        question="What single main reason do non-users report?", construct="experience/barriers",
        source="Eurostat isoc_ai_iaiuxr",
        source_url="https://ec.europa.eu/eurostat/databrowser/view/isoc_ai_iaiuxr/default/table?lang=en",
        sample_family="EU_ICT_2025",
        population="Recent internet users who did not use generative AI in the last 3 months (item B7)",
        geography="2 aggregates plus 36 countries/territories; EU_USE list plus ME; Iceland absent",
        fieldwork_or_reference="2025 only; previous three months",
        unit="people; indic_is I_IUAIX_NUNN / NUUNK / NUUSE / NUSEC / NUOTH",
        denominator="use published PC_IND_IUAIX cells; the base is not reliably reconstructible from the use table (up to 6.52 pp divergence in BE, SE, NO, LU)",
        gender_measure="same ind_type sex codes as EU_USE; H2 Sex Male/Female only",
        ai_definition="generative AI as in EU_USE",
        comparison_group="source-specific non-user comparisons",
        verification_status="file-verified 2026-10-01 (pilot); re-downloaded 2026-10-01, same SHA-256 8901c5c9...8ef4; single-main-reason definition confirmed against the 2025 model questionnaire",
        audit_record=f"{A}/pilot-corrections.md; evidence/pilot-2026-10-01/eurostat-profile.md",
        access_status="open bulk download; DOI 10.2908/ISOC_AI_IAIUXR; EIGE mirror reports 53280 values against 54825 in the primary (unexplained)",
        redistribution_status="as EU_USE",
        uncertainty="no published standard errors; u flag only",
        missingness_or_selection="single-response item; five reasons sum to about 99 per cent of the base, residual consistent with item non-response (cause not established); reasons are not causal explanations of the adoption gap",
        next_check="C2 cross-table base divergence remains unresolved: country-specific notes (CIRCABC) returned 404 and the compilers' manual exists only for the 2024 survey; resolve or drop the EIGE mirror",
        new_check_this_setup="false",
        joint_fields="as EU_USE",
        design_weights_precision="as EU_USE",
        evidence_level="file-verified-aggregate", id_status="existing", lead_slot="",
    ),
    dict(
        indicator_id="UK_DSIT_USE",
        question="Who reports using generative AI in the UK?", construct="participation",
        source="DSIT Public Engagement Survey 2025/2026, artificial intelligence tables",
        source_url="https://www.gov.uk/government/statistics/dsit-public-engagement-survey-20252026",
        sample_family="UK_DSIT_PES_2025_2026",
        population="UK adults aged 16 and over",
        geography="United Kingdom (1 country; rural/urban split excludes Northern Ireland)",
        fieldwork_or_reference="fieldwork November 2025 - March 2026; use in the last three months",
        unit="people; Table_E5 'Generative AI user' composite",
        denominator="all adults (Table_E5); Table_E7 purposes are online-only, multiple response, with separate weights and item-specific bases",
        gender_measure="provider categories Male / Female / Identify in another way / Prefer not to say (online GENDER item; paper Q5)",
        ai_definition="note 1 composite: used in the last three months at least one of text/speech generators, image/video/music tools, or autonomous workplace AI systems - broader than the Eurostat item",
        comparison_group="UK national module only; not comparable with Eurostat",
        verification_status="file-verified 2026-10-01: workbook re-downloaded independently, byte-identical (325288 bytes, SHA-256 a34ed705...610a); coordinator extractor reproduces Table_E5 cells; technical report and paper questionnaire read",
        audit_record=f"{A}/profiles/uk-dsit-outstanding-checks.md; landscape-v1/coordination/UK-DSIT.md",
        access_status="open download; no registration",
        redistribution_status="Open Government Licence v3.0 except where otherwise stated; check the exception clause and attribute before republication",
        uncertainty="technical report documents 95 per cent logit confidence intervals in the published tables and a design effect of 1.67, but the AI workbook columns contain no interval; do not derive precision from bases",
        missingness_or_selection="suppression where fewer than 30 respondents answered or fewer than 5 gave a response; third gender category base is 99 unweighted (141 weighted) and very imprecise; raking matches margins only",
        next_check="decide whether to display a composite that mixes generative and autonomous workplace AI; audit Table_E7 separately; ask whether a gender-by-age table or a microdata deposit exists",
        new_check_this_setup="true",
        joint_fields="Table_E5 publishes one-way subgroup rows only; no published gender-by-age cell despite gender-by-age being a weighting margin",
        design_weights_precision="Address Based Online Sampling push-to-web, stratified sample of 106612 addresses, online or paper; three-step weighting ending in RIM calibration to LFS and mid-year estimates; design effect 1.67",
        evidence_level="file-verified-aggregate", id_status="new-this-programme (coordinator-proposed)", lead_slot="1",
    ),
    dict(
        indicator_id="BR_CETIC_USE",
        question="Who among Brazilian internet users reports using AI tools?", construct="participation",
        source="Cetic.br / NIC.br, TIC Domicilios 2025, individuals table M1",
        source_url="https://www.cetic.br/pt/tics/domicilios/2025/individuos/M1/",
        sample_family="BR_CETIC_TICDOM_2025",
        population="Internet users aged 10 and over resident in permanent private households in Brazil",
        geography="Brazil (1 country)",
        fieldwork_or_reference="fieldwork March-September 2025; last three months before interview",
        unit="people; percentage of internet users, with population totals also published",
        denominator="internet users aged 10+ (used the internet at least once in the previous three months, ITU definition)",
        gender_measure="provider SEXO rows Masculino / Feminino; no third category published",
        ai_definition="item C13A: used an artificial-intelligence tool such as ChatGPT, Copilot, Gemini or Meta AI in WhatsApp in the last 3 months - an AI-tool stimulus published under a generative-AI label",
        comparison_group="Brazil national module only; not comparable with Eurostat (age floor 10, internet-user denominator, different stimulus)",
        verification_status="file-verified 2026-10-01: provider table bundle v1.0 (SHA-256 9ca6638c...dd930) parsed by check_cetic.py; proportions, totals and margins of error extracted; rounded website cells reproduce",
        audit_record=f"{A}/profiles/brazil-cetic.md; {A}/checks/cetic-published-cells.json",
        access_status="open download; no registration; respondent microdata CSV exists and was deliberately not downloaded",
        redistribution_status="download-page dataset entry states CC BY 4.0 for version 1.0; provider indicator pages also link CC BY-SA 4.0; pin the file-level licence and attribute NIC.br (2025) as printed",
        uncertainty="provider publishes a margin-of-error table: use 'Yes' male 34.79 +/- 3.29 pp, female 30.49 +/- 2.78 pp at 95 per cent",
        missingness_or_selection="27177 households approached against 40408 counted; 24535 individual interviews; separate 'does not know' and 'did not answer' columns are not gender categories",
        next_check="confirm whether the Portuguese volume carries item-level notes absent from the English volume; decide publication licence",
        new_check_this_setup="true",
        joint_fields="marginal breakdowns only; no published sex-by-age or sex-by-education cell; do not construct one from margins",
        design_weights_precision="stratified clustered probability sample in 3-4 stages from IBGE register-based census sectors; CAPI face-to-face; calibrated weights; margins of error published per cell",
        evidence_level="file-verified-aggregate", id_status="new-this-audit", lead_slot="",
    ),
    dict(
        indicator_id="BR_CETIC_PURPOSE",
        question="For what purposes do Brazilian users use generative AI?", construct="patterns",
        source="Cetic.br / NIC.br, TIC Domicilios 2025, individuals table M2",
        source_url="https://www.cetic.br/pt/tics/domicilios/2025/individuos/M2/",
        sample_family="BR_CETIC_TICDOM_2025",
        population="Internet users aged 10+ who used generative AI",
        geography="Brazil (1 country)",
        fieldwork_or_reference="as BR_CETIC_USE",
        unit="people; percentage of generative-AI users",
        denominator="internet users who used generative AI (multiple response, so purposes do not sum to 100)",
        gender_measure="as BR_CETIC_USE", ai_definition="as BR_CETIC_USE",
        comparison_group="within Brazil and stated denominator only",
        verification_status="file-verified 2026-10-01 (same bundle and script as BR_CETIC_USE)",
        audit_record=f"{A}/profiles/brazil-cetic.md; {A}/checks/cetic-published-cells.json",
        access_status="as BR_CETIC_USE", redistribution_status="as BR_CETIC_USE",
        uncertainty="margins of error published per cell (for example professional use male 52.23 +/- 5.22 pp, female 48.68 +/- 5.00 pp)",
        missingness_or_selection="multiple response; base is users only, so purpose shares are conditional on adoption",
        next_check="state the conditional base wherever a purpose is displayed", new_check_this_setup="true",
        joint_fields="as BR_CETIC_USE",
        design_weights_precision="as BR_CETIC_USE",
        evidence_level="file-verified-aggregate", id_status="new-this-audit", lead_slot="",
    ),
    dict(
        indicator_id="BR_CETIC_NONUSE",
        question="Which reasons do Brazilian non-users give?", construct="experience/barriers",
        source="Cetic.br / NIC.br, TIC Domicilios 2025, individuals table M3",
        source_url="https://www.cetic.br/pt/tics/domicilios/2025/individuos/M3/",
        sample_family="BR_CETIC_TICDOM_2025",
        population="Internet users aged 10+ who did not use generative AI",
        geography="Brazil (1 country)",
        fieldwork_or_reference="as BR_CETIC_USE",
        unit="people; percentage of non-using internet users",
        denominator="internet users who did not use generative AI",
        gender_measure="as BR_CETIC_USE", ai_definition="as BR_CETIC_USE",
        comparison_group="within Brazil only; NOT comparable with Eurostat EU_NONUSE",
        verification_status="file-verified 2026-10-01 (same bundle and script)",
        audit_record=f"{A}/profiles/brazil-cetic.md; {A}/checks/cetic-published-cells.json",
        access_status="as BR_CETIC_USE", redistribution_status="as BR_CETIC_USE",
        uncertainty="margins of error published per cell",
        missingness_or_selection="MULTIPLE RESPONSE: the male row sums to about 239 per cent of its base, so these are not Eurostat's single main reason and must never be differenced against it",
        next_check="label the multiple-response base prominently if displayed beside EU_NONUSE",
        new_check_this_setup="true",
        joint_fields="as BR_CETIC_USE", design_weights_precision="as BR_CETIC_USE",
        evidence_level="file-verified-aggregate", id_status="new-this-audit", lead_slot="",
    ),
    dict(
        indicator_id="KR_NIA_USE",
        question="Who in Korea has experienced a generative-AI service?", construct="participation",
        source="Ministry of Science and ICT / NIA, 2025 Survey on the Internet Usage, statistical table 105",
        source_url="https://www.nia.or.kr/site/nia_kor/ex/bbs/View.do?bcIdx=29580&cbIdx=99870",
        sample_family="KR_NIA_INTERNET_2025",
        population="Internet users aged 12 and over (internet use within the last year)",
        geography="Republic of Korea (1 country)",
        fieldwork_or_reference="fieldwork 17 October - 12 December 2025; reference date 1 July 2025; generative-AI reference window: within the last 1 year",
        unit="people; percentage of internet users aged 12+",
        denominator="internet users aged 12+ who used the internet within the last year",
        gender_measure="Gender rows Male / Female; no third category documented in the English volumes",
        ai_definition="experience of generative-AI services, prompted by named services (ChatGPT, Gemini, Copilot, CLOVA X, other)",
        comparison_group="Korea national module only; one-year window is not Eurostat's three months",
        verification_status="file-verified 2026-10-01: English statistical-table PDF (SHA-256 12ec5ffe...8bc00) parsed by check_korea.py; male 48.7, female 40.3; gender-by-age block present",
        audit_record=f"{A}/profiles/korea-nia.md; {A}/checks/korea-published-cells.json",
        access_status="open download from the provider notice page (file endpoint requires the notice page as referer); no registration",
        redistribution_status="UNRESOLVED: the English report states NIA holds copyright and restricts unauthorised reproduction; no open licence found in the inspected volumes; quote with attribution, check terms before republishing tables",
        uncertainty="survey-level sampling error published only (internet usage rate +/- 0.19 pp at 95 per cent); no table-level or subgroup error for the generative-AI tables",
        missingness_or_selection="military personnel, long-term overseas residents, dormitory residents and inmates excluded; substitute households used on refusal",
        next_check="resolve reuse terms; extract printed table 134 to complete the non-use reasons; check whether KOSIS publishes the same cells with an explicit licence",
        new_check_this_setup="true",
        joint_fields="PUBLISHED sex-by-age cells (Male/Female x 12-19, 20s, 30s, 40s, 50s, 60s, 70+); occupation rows are not crossed with sex",
        design_weights_precision="approved national statistics; stratified multi-stage cluster sample; frame 2023 register-based census; 22691 households and 50750 members aged 3+; face-to-face; post-stratification to 2025 projections",
        evidence_level="file-verified-aggregate", id_status="new-this-audit", lead_slot="3",
    ),
    dict(
        indicator_id="KR_NIA_SERVICE",
        question="Which generative-AI services are used in Korea?", construct="patterns",
        source="Ministry of Science and ICT / NIA, 2025 Survey on the Internet Usage, statistical table 106",
        source_url="https://www.nia.or.kr/site/nia_kor/ex/bbs/View.do?bcIdx=29580&cbIdx=99870",
        sample_family="KR_NIA_INTERNET_2025",
        population="Internet users aged 12 and over", geography="Republic of Korea (1 country)",
        fieldwork_or_reference="as KR_NIA_USE",
        unit="people; percentage of internet users aged 12+",
        denominator="internet users aged 12+ (multiple response across services)",
        gender_measure="as KR_NIA_USE",
        ai_definition="named services: ChatGPT, Gemini, Copilot, CLOVA X, other",
        comparison_group="within Korea only; service-named items have no Eurostat counterpart",
        verification_status="file-verified 2026-10-01 (same file and script): ChatGPT male 45.5, female 38.0",
        audit_record=f"{A}/profiles/korea-nia.md; {A}/checks/korea-published-cells.json",
        access_status="as KR_NIA_USE", redistribution_status="as KR_NIA_USE",
        uncertainty="as KR_NIA_USE", missingness_or_selection="multiple response; service shares are not additive",
        next_check="purposes are published per service (tables 113+), not as one purpose question; audit before any purpose indicator",
        new_check_this_setup="true", joint_fields="as KR_NIA_USE",
        design_weights_precision="as KR_NIA_USE",
        evidence_level="file-verified-aggregate", id_status="new-this-audit", lead_slot="3",
    ),
    dict(
        indicator_id="KR_NIA_NONUSE",
        question="Why do Korean internet users not use generative AI?", construct="experience/barriers",
        source="Ministry of Science and ICT / NIA, 2025 Survey on the Internet Usage, statistical tables 133-134",
        source_url="https://www.nia.or.kr/site/nia_kor/ex/bbs/View.do?bcIdx=29580&cbIdx=99870",
        sample_family="KR_NIA_INTERNET_2025",
        population="Internet users aged 12+ who have not experienced a generative-AI service",
        geography="Republic of Korea (1 country)", fieldwork_or_reference="as KR_NIA_USE",
        unit="people; percentage of non-experiencing internet users",
        denominator="internet users aged 12+ not experienced",
        gender_measure="as KR_NIA_USE", ai_definition="as KR_NIA_USE",
        comparison_group="within Korea only",
        verification_status="partially file-verified 2026-10-01: three reason columns extracted from table 133 (male 50.6 / 16.8 / 15.7; female 48.4 / 19.9 / 16.4); the column set continues in table 134, not extracted",
        audit_record=f"{A}/profiles/korea-nia.md; {A}/checks/korea-published-cells.json",
        access_status="as KR_NIA_USE", redistribution_status="as KR_NIA_USE",
        uncertainty="as KR_NIA_USE",
        missingness_or_selection="the extracted three columns do not exhaust the base (total row sums to 84.1), so they are an incomplete reason distribution",
        next_check="extract table 134 before displaying any reason distribution", new_check_this_setup="true",
        joint_fields="as KR_NIA_USE", design_weights_precision="as KR_NIA_USE",
        evidence_level="file-verified-aggregate (incomplete column set)", id_status="new-this-audit", lead_slot="3",
    ),
    dict(
        indicator_id="CA_CSWC_WORK",
        question="Do Canadian workers use generative AI at work, by gender?", construct="workplace use",
        source="Statistics Canada, Canadian Survey on Working Conditions (article 75-006-X 2026001/00007)",
        source_url="https://www150.statcan.gc.ca/n1/pub/75-006-x/2026001/article/00007-eng.htm",
        sample_family="CA_CSWC_2024_2025",
        population="Workers aged 15-69 in the provinces; excludes territories, reserves and other settlements, regular Armed Forces, unpaid family workers",
        geography="Canada, provinces only (1 country, partial coverage)",
        fieldwork_or_reference="four collection periods September 2024 - July 2025, averaged; use in the previous 12 months in the main job or business",
        unit="people (workers)", denominator="employed population aged 15-69 in the provinces",
        gender_measure="two aggregated categories Female+ / Male+: non-binary respondents are distributed into the two categories for confidentiality, denoted by '+'",
        ai_definition="generative AI tools used as part of the main job or business",
        comparison_group="Canada workplace module only",
        verification_status="published findings verified 2026-10-01 from the primary article: crude use women 22 per cent, men 22 per cent; adjusted Male+ odds ratio 1.15 (95 per cent CI 1.02-1.29) vs Female+ reference, Table A.1",
        audit_record=f"{A}/profiles/canada-statcan.md",
        access_status="open article; no data table or microdata audited",
        redistribution_status="Statistics Canada Open Licence documented but licence text not re-read this pass",
        uncertainty="confidence interval published for the odds ratio only; no interval published for the crude rates",
        missingness_or_selection="measures use, not intensity or frequency; the '+' categories are not a measure of non-binary experience",
        next_check="pin the cells to a StatCan table/vector identifier and hash; read the open-licence text",
        new_check_this_setup="true",
        joint_fields="published gender cells are crude rates; the adjusted estimate is a model coefficient, not a cell; do not convert an odds ratio into a percentage-point gap or a causal effect",
        design_weights_precision="probability survey averaged over four waves; design documented in the article's methods; weights not inspected",
        evidence_level="published-finding-only", id_status="new-this-audit", lead_slot="",
    ),
    dict(
        indicator_id="CA_LFS_AI_2026",
        question="How does workplace generative-AI use vary by occupational AI exposure and gender?",
        construct="workplace use",
        source="Statistics Canada, March 2026 Labour Force Survey AI supplement (The Daily, 30 July 2026)",
        source_url="https://www150.statcan.gc.ca/n1/daily-quotidien/260730/dq260730b-eng.htm",
        sample_family="CA_LFS_SUP_2026_03",
        population="Respondents aged 15-69 in the provinces; excludes reserves, regular Armed Forces, institutional residents",
        geography="Canada, provinces only (1 country, partial coverage)",
        fieldwork_or_reference="March 2026 supplement; use at work in the past 12 months",
        unit="people (workers)", denominator="workers within each occupational exposure/complementarity group",
        gender_measure="men / women as reported in the release; no third category documented",
        ai_definition="generative AI tools used at work",
        comparison_group="within this release only; NOT a CSWC update and not a trend with it",
        verification_status="published findings verified 2026-10-01: high-exposure/high-complementarity men 57.0 vs women 50.9; high-exposure/low-complementarity men 52.9 vs women 41.2 (11.7 pp)",
        audit_record=f"{A}/profiles/canada-statcan.md",
        access_status="open release; no data table or microdata audited",
        redistribution_status="Statistics Canada Open Licence documented but text not re-read this pass",
        uncertainty="no interval or coefficient of variation published in the release text",
        missingness_or_selection="exposure/complementarity groups are a modelled occupational classification whose sex composition differs; a within-group gap is not an overall gap",
        next_check="pin to the published table; check whether CVs are released; keep separate from CA_CSWC_WORK",
        new_check_this_setup="true",
        joint_fields="gender crossed with occupational exposure group only",
        design_weights_precision="LFS supplement design; not inspected",
        evidence_level="published-finding-only", id_status="new-this-audit", lead_slot="6",
    ),
    dict(
        indicator_id="PEW_GLOBAL_ATT",
        question="How do expectations about AI differ by gender across countries?", construct="attitudes",
        source="Pew Research Center, Spring 2026 Global Attitudes Survey (AI report, 17 September 2026)",
        source_url="https://www.pewresearch.org/global/2026/09/17/globally-more-people-expect-ai-to-cause-job-loss-than-growth/",
        sample_family="PEW_GLOBAL_AI_2026",
        population="Adults in each surveyed country; samples designed to represent each country's adult population",
        geography="36 countries plus the United States (37 country samples; no regional aggregate published)",
        fieldwork_or_reference="non-US fieldwork 8 February - 13 May 2026; US from ATP W187 (17-23 February 2026) and W195 (22-28 June 2026)",
        unit="people (respondents)", denominator="adults per country",
        gender_measure="men / women; no third category documented",
        ai_definition="AI in general; expectations and concern, NOT generative-AI use",
        comparison_group="within this study and item only; never beside generative-AI use rates",
        verification_status="documentation-verified 2026-10-01: 42151 respondents across 36 countries; US from two separate surveys; appendix detailed tables are by age, education and income; gender appears only as selected statistically significant differences (11 countries for the fewer-jobs item, France 10 pp)",
        audit_record=f"{A}/profiles/pew-global-and-us.md",
        access_status="report, topline and methodology open; respondent-level data require an account and terms acceptance (not attempted)",
        redistribution_status="unverified; quote published findings with attribution",
        uncertainty="per-country margins of error published in the topline; gender subgroup cells are not published with errors",
        missingness_or_selection="a 37-country study is not a world sample; no country-by-gender matrix exists",
        next_check="if a gender attitudes panel is wanted, list the countries named in the published gender chart rather than building a matrix",
        new_check_this_setup="true",
        joint_fields="country-by-gender cells not published for every item",
        design_weights_precision="national probability designs described in the methodology; US via the American Trends Panel",
        evidence_level="documentation-verified", id_status="new-this-audit", lead_slot="",
    ),
    dict(
        indicator_id="PEW_GENDER",
        question="How do use and experiences differ in the US?", construct="participation/experience",
        source="Pew Research Center, Americans and AI 2026 (17 June 2026)",
        source_url="https://www.pewresearch.org/internet/2026/06/17/the-gender-gap-in-ai/",
        sample_family="PEW_ATP_W187",
        population="US adults", geography="United States (1 country)",
        fieldwork_or_reference="ATP Wave 187, fieldwork 17-23 February 2026; published 17 June 2026",
        unit="people (respondents)", denominator="question-specific; chatbot items are ever-use or frequency",
        gender_measure="men / women as reported; item wording not inspected",
        ai_definition="chatbots and item-specific AI; ever-use is not last-three-months use",
        comparison_group="within wave and definition; not comparable with Eurostat",
        verification_status="documentation-verified 2026-10-01: wave number 187 confirmed on the methodology page; 5119 of 5854 sampled panellists responded; online n=4930 and telephone n=189 by SSRS",
        audit_record=f"{A}/profiles/pew-global-and-us.md",
        access_status="report and topline open; microdata require an account (not attempted)",
        redistribution_status="unverified; quote published findings",
        uncertainty="topline reports a margin of error; subgroup precision not audited",
        missingness_or_selection="panel-based; oversample of non-Hispanic Asian adults weighted back",
        next_check="read the W187 topline bases if a US indicator is displayed with uncertainty",
        new_check_this_setup="true",
        joint_fields="SAME WAVE as the US February data in PEW_GLOBAL_ATT; not independent evidence",
        design_weights_precision="American Trends Panel, probability-recruited; weighting documented by the publisher",
        evidence_level="documentation-verified", id_status="existing", lead_slot="",
    ),
    dict(
        indicator_id="MELB_KPMG_TRUST",
        question="Do trust, attitudes and AI use at work differ by gender across countries?",
        construct="attitudes/workplace use",
        source="University of Melbourne and KPMG, Trust, attitudes and use of AI: a global study 2025",
        source_url="https://mbs.edu/-/media/PDF/Research/Trust_in_AI_Report.pdf",
        sample_family="MELB_KPMG_2025",
        population="Online panel respondents aged 18+ in 47 countries and jurisdictions",
        geography="47 countries/jurisdictions (no probability sampling claim; nationally representative on age, gender and region within a 5 per cent margin, with stated exceptions)",
        fieldwork_or_reference="online fieldwork November 2024 - mid-January 2025",
        unit="people (respondents)", denominator="per-country samples of 1001-1098; respondents randomly allocated to one of four AI framings, so the generative-AI framing is seen by roughly a quarter of each sample",
        gender_measure="women / men / other reported genders; other-gender options were NOT offered in some countries (for example UAE, Saudi Arabia)",
        ai_definition="OECD-based general AI definition plus one randomly allocated application: generative AI, healthcare AI, HR AI or AI in general",
        comparison_group="within this study only; broad AI is not generative AI",
        verification_status="documentation-verified 2026-10-01 from the report PDF: 48340 respondents, 47 countries; Appendix 3 country tables carry NO gender split; gender appears as sample composition plus a global statement of no gender differences in AI use or attitudes at work",
        audit_record=f"{A}/profiles/multicountry-and-platform-leads.md",
        access_status="open PDF", redistribution_status="CC BY-NC-SA 4.0, non-commercial only; DOI 10.26188/28822919",
        uncertainty="no published interval for any gender cell; per-country n implies roughly 125 respondents per sex within the generative-AI framing",
        missingness_or_selection="online panel; over-representation of university-educated respondents in emerging economies; difficulty reaching over-65s in eight countries",
        next_check="treat the global gender null as an attributed published finding; do not seek a country-by-gender matrix from this source",
        new_check_this_setup="true",
        joint_fields="NO usable country-by-gender outcome cells published",
        design_weights_precision="quota-based online panel with stated representativeness targets; MANCOVA robustness checks reported by the authors",
        evidence_level="documentation-verified", id_status="new-this-audit", lead_slot="",
    ),
    dict(
        indicator_id="AU_ADII_GENAI",
        question="Who in Australia uses generative AI?", construct="participation",
        source="Australian Digital Inclusion Index 2025 / Australian Internet Usage Survey 2024",
        source_url="https://digitalinclusionindex.org.au/wp-content/uploads/2025/10/ADII-Report-2025_V6-Remediated.pdf",
        sample_family="AU_ADII_2025",
        population="Australians aged 18+ (survey includes a First Nations booster)",
        geography="Australia (1 country)",
        fieldwork_or_reference="data year 2024; report published 2025; 'recent' use (window not audited)",
        unit="people", denominator="all Australians for the headline rate (45.6 per cent); recent users for types of use",
        gender_measure="dashboard exposes a gender filter; NO gender cell for generative AI is published in the report",
        ai_definition="generative-AI tools (case study 1)",
        comparison_group="Australia national module only",
        verification_status="documentation-only 2026-10-01: report verified (age, education, occupation, language, disability and remoteness breakdowns published); gender cells not obtained. Dashboard requires clicking an agreement before data are shown and terms were NOT accepted; the index site page returned 404",
        audit_record=f"{A}/profiles/multicountry-and-platform-leads.md",
        access_status="report open; dashboard behind a terms-acceptance click (not accepted under assignment limits)",
        redistribution_status="CC BY-NC-SA 4.0 with a prescribed citation",
        uncertainty="not published in the inspected report",
        missingness_or_selection="no verified sex-disaggregated generative-AI cell for Australia in this audit",
        next_check="seek a provider-published gender table, or an authorised decision on accepting the dashboard terms",
        new_check_this_setup="true",
        joint_fields="unknown; nothing acquired",
        design_weights_precision="not audited",
        evidence_level="documentation-only", id_status="new-this-audit", lead_slot="2",
    ),
    dict(
        indicator_id="SIGNALS_TOPIC",
        question="How does message representation vary across topics?", construct="platform use patterns",
        source="OpenAI Signals", source_url="https://openai.com/signals/data-download/",
        sample_family="OPENAI_SIGNALS_V2",
        population="Eligible individual ChatGPT messages (Free, Go, Plus, Pro; excludes enterprise and Codex)",
        geography="global with selected country panels; completeness not re-verified",
        fieldwork_or_reference="sample of messages July 2024 - June 2026 per the publisher's description",
        unit="MESSAGES, not people", denominator="eligible messages in the specified topic/place/month",
        gender_measure="name-associated proxy: share of messages from users with traditionally masculine or traditionally feminine names, excluding other names; NOT self-reported sex or gender",
        ai_definition="ChatGPT", comparison_group="within consistent platform panels only",
        verification_status="documentation-only 2026-10-01: direct requests to three Signals URLs returned HTTP 403; publisher page content obtained via the search index shows the citation is still 'OpenAI Signals v2.0' with data dictionary README v1.1, so the prior bundle is NOT shown to be superseded",
        audit_record=f"{A}/profiles/multicountry-and-platform-leads.md; {A}/pilot-corrections.md",
        access_status="BLOCKED to this session (403); open download claimed by the publisher",
        redistribution_status="publisher states CC BY 4.0 with a suggested citation",
        uncertainty="differential-privacy noise with a stated budget; subgroup precision not established",
        missingness_or_selection="platform users are not a population sample; suppression and selected countries; messages are not people",
        next_check="obtain the release file through a permitted route and verify panel completeness before any display",
        new_check_this_setup="true",
        joint_fields="message-level categories only; no person-level sex/gender",
        design_weights_precision="no survey design; privacy-noised aggregates",
        evidence_level="documentation-only (blocked download)", id_status="existing", lead_slot="",
    ),
    dict(
        indicator_id="ILO_EXPOSURE",
        question="How is occupational exposure distributed?", construct="potential occupational exposure",
        source="ILO Working Paper 140, refined global index of occupational exposure to generative AI",
        source_url="https://www.ilo.org/publications/generative-ai-and-jobs-refined-global-index-occupational-exposure",
        sample_family="ILO_GENAI_2025",
        population="Occupations and employment composition, not individuals",
        geography="global in ambition; verified country coverage unknown",
        fieldwork_or_reference="working paper dated 20 May 2025",
        unit="jobs / employment composition", denominator="employment in mapped occupations",
        gender_measure="sex composition of occupations; NOT the gender of any AI user",
        ai_definition="modelled potential exposure to generative AI",
        comparison_group="within compatible employment and mapping coverage only",
        verification_status="documentation-only 2026-10-01: publication page verified (29753 Polish-classification tasks sampled, survey of 1640 workers, 52558 task data points, Delphi rounds); page offers PDF and EPUB only and no country-year series; ILOSTAT topic page returned HTTP 403",
        audit_record=f"{A}/profiles/multicountry-and-platform-leads.md",
        access_status="publication open; data series not located (two routes attempted)",
        redistribution_status="unverified",
        uncertainty="model and mapping uncertainty; no causal job-loss estimate",
        missingness_or_selection="task input anchored in one national occupational classification; occupational sex shares must never be used to infer individual gender",
        next_check="locate the country-year series through a permitted ILOSTAT route; keep exposure separate from adoption and from welfare claims",
        new_check_this_setup="true",
        joint_fields="employment by occupation and sex, from employment statistics, not from AI users",
        design_weights_precision="expert and worker elicitation plus modelling; not a population survey",
        evidence_level="documentation-only", id_status="existing", lead_slot="",
    ),
    dict(
        indicator_id="EWCS_WORK",
        question="How do workplace conditions relate to use?", construct="workplace opportunity",
        source="Eurofound, European Working Conditions Survey 2024",
        source_url="https://www.eurofound.europa.eu/en/surveys/european-working-conditions-surveys",
        sample_family="EWCS_2024",
        population="Workers; analytic sample unverified", geography="European countries (prior audit: 35)",
        fieldwork_or_reference="2024; national field dates to check",
        unit="workers", denominator="eligible workers", gender_measure="respondent field not verified",
        ai_definition="question wording not verified", comparison_group="source-specific worker comparisons",
        verification_status="carried forward unverified; access route re-attempted 2026-10-01 (Eurofound survey pages returned HTTP 429 twice; UK Data Service catalogue page returned a script-only shell)",
        audit_record=f"{A}/AUDIT-REPORT.md; concept-and-feasibility.md",
        access_status="registered researcher access under an end-user licence; microdata not acquired",
        redistribution_status="repository terms not inspected",
        uncertainty="design and weights not inspected", missingness_or_selection="routing and joint cells not checked",
        next_check="retry the provider pages outside a rate-limit window; do not request data without a separate authorisation",
        new_check_this_setup="false",
        joint_fields="unknown", design_weights_precision="not inspected",
        evidence_level="blocked (access-gated)", id_status="existing", lead_slot="",
    ),
    dict(
        indicator_id="EB_SUPPORT",
        question="Who receives digital workplace support?", construct="workplace opportunity/attitudes",
        source="Eurobarometer 101.4 / Special 554",
        source_url="https://www.gesis.org/en/eurobarometer-data-service/data-and-documentation/standard-special-eb/study-overview/eurobarometer-1014-za8844-april-may-2024",
        sample_family="EB_101_4", population="Relevant employed or respondent subsamples",
        geography="EU coverage to verify", fieldwork_or_reference="2024 fieldwork; later publication",
        unit="respondents", denominator="question-routing dependent", gender_measure="released variable coding to verify",
        ai_definition="broad digital/AI; does not isolate generative AI",
        comparison_group="source-specific broad-digital comparisons",
        verification_status="carried forward unverified; not re-attempted in this audit (GESIS returned HTTP 403 to the related ISSP request, so the archive route is presumed similar and was not retried)",
        audit_record=f"{A}/AUDIT-REPORT.md; additional-sources-audit-2026-09-30.md",
        access_status="registered archive access; not acquired", redistribution_status="archive terms not inspected",
        uncertainty="design and subgroup precision unverified",
        missingness_or_selection="digital and AI wording may be combined",
        next_check="map support questions and joint gender fields if an authorised acquisition is ever scoped",
        new_check_this_setup="false", joint_fields="unknown", design_weights_precision="not inspected",
        evidence_level="carried-forward-unverified", id_status="existing", lead_slot="",
    ),
    dict(
        indicator_id="CEDEFOP_SKILLS",
        question="What AI training do workers report?", construct="workplace skills",
        source="Cedefop AI skills survey 2024",
        source_url="https://www.cedefop.europa.eu/en/publications/9201",
        sample_family="CEDEFOP_AI_2024",
        population="5342 employees aged 16-64; excludes self-employed", geography="11 EU countries",
        fieldwork_or_reference="February-May 2024", unit="employees", denominator="eligible employees",
        gender_measure="joint respondent field unverified", ai_definition="AI; item wording unverified",
        comparison_group="source-specific employee comparisons",
        verification_status="carried forward unverified; no respondent-level release located in the prior audit and none sought here",
        audit_record=f"{A}/AUDIT-REPORT.md; additional-sources-audit-2026-09-30.md",
        access_status="reusable respondent file not located", redistribution_status="unverified",
        uncertainty="unverified", missingness_or_selection="broad AI, not generative AI; limited country set; not ESJS2",
        next_check="only pursue if a published gender table exists; otherwise leave as literature",
        new_check_this_setup="false", joint_fields="unknown", design_weights_precision="not inspected",
        evidence_level="carried-forward-unverified", id_status="existing", lead_slot="",
    ),
    dict(
        indicator_id="ISSP_ATTITUDES",
        question="How do attitudes differ across settings?", construct="attitudes",
        source="ISSP 2024 Digital Societies (release ZA10020)",
        source_url="https://issp.org/members/member-states/",
        sample_family="ISSP_DIGITAL_2024",
        population="National samples; participating countries unknown",
        geography="UNKNOWN for the release; programme membership spans 41 countries, which is not participation",
        fieldwork_or_reference="country field dates vary; 2026 release",
        unit="respondents", denominator="eligible respondents", gender_measure="harmonised field not inspected",
        ai_definition="broad AI and robotics", comparison_group="within harmonised questions after a coverage audit",
        verification_status="blocked; re-attempted 2026-10-01: GESIS study page search.gesis.org/research_data/ZA10020 returned HTTP 403 (the pilot had three prior 403s); issp.org membership page remains the only route",
        audit_record=f"{A}/AUDIT-REPORT.md; evidence/pilot-2026-10-01/geographic-coverage.csv",
        access_status="registered download; not acquired", redistribution_status="archive terms not inspected",
        uncertainty="design and weights unverified",
        missingness_or_selection="optional items and field dates vary; broad AI is not generative-AI adoption",
        next_check="obtain the release country list through a permitted non-blocked route before any coverage claim",
        new_check_this_setup="false", joint_fields="unknown", design_weights_precision="not inspected",
        evidence_level="blocked (access-gated)", id_status="existing", lead_slot="",
    ),
    dict(
        indicator_id="ECB_WORK",
        question="What workplace AI use and savings are observable?", construct="work use/returns",
        source="ECB Consumer Expectations Survey",
        source_url="https://www.ecb.europa.eu/stats/ecb_surveys/consumer_exp_survey/html/data_methodological.en.html",
        sample_family="ECB_CES_WORK_AI", population="Published report sample; public-variable coverage unresolved",
        geography="11 countries in the cited report", fieldwork_or_reference="module dates to check",
        unit="respondents", denominator="module routing unverified",
        gender_measure="gender metadata present; joint AI fields not found",
        ai_definition="published workplace AI measure", comparison_group="not yet eligible for comparisons",
        verification_status="carried forward unverified; not re-attempted in this audit",
        audit_record=f"{A}/AUDIT-REPORT.md; additional-sources-audit-2026-09-30.md",
        access_status="general microdata route does not establish workplace-module access",
        redistribution_status="unverified", uncertainty="unverified",
        missingness_or_selection="report exists but the inspected public guide lacks the relevant fields",
        next_check="clarify the release before treating any workplace AI variable as available",
        new_check_this_setup="false", joint_fields="unknown", design_weights_precision="not inspected",
        evidence_level="carried-forward-unverified", id_status="existing", lead_slot="",
    ),
    dict(
        indicator_id="RPS_USE_RETURNS",
        question="How does use relate to reported time savings?", construct="intensity/self-reported returns",
        source="Bick, Blandin and Deming, Real-Time Population Survey",
        source_url="https://sites.google.com/view/blandin/research",
        sample_family="RPS_GENAI", population="US survey sample", geography="United States (1 country)",
        fieldwork_or_reference="wave-specific", unit="respondents",
        denominator="eligible workers or users depending on the item", gender_measure="joint fields unverified",
        ai_definition="generative AI", comparison_group="not eligible for novel reuse pending permission",
        verification_status="blocked on reuse terms; unchanged in this audit, which made no contact and submitted no agreement",
        audit_record=f"{A}/AUDIT-REPORT.md; additional-sources-audit-2026-09-30.md",
        access_status="replication-only download terms; no data acquired",
        redistribution_status="inspected terms restrict novel reuse without explicit permission",
        uncertainty="unverified", missingness_or_selection="self-reports; released fields unaudited",
        next_check="a permitted novel-use route requires an owner contact, which this assignment does not authorise",
        new_check_this_setup="false", joint_fields="unknown", design_weights_precision="not inspected",
        evidence_level="blocked (reuse terms)", id_status="existing", lead_slot="",
    ),
    dict(
        indicator_id="SPAIN_MOTIVATION",
        question="What do respondents recall bringing them to ChatGPT?", construct="starting motivations",
        source="Ochoa, Fernandez Melero and Revilla, OSF survey", source_url="https://osf.io/gpc5u/",
        sample_family="SPAIN_CHATGPT_OSF_GPC5U", population="Opt-in quota sample; 2102 completes in the prior audit",
        geography="Spain (1 country)", fieldwork_or_reference="questionnaire and fieldwork dates to confirm",
        unit="respondents and short text responses", denominator="question-routing dependent",
        gender_measure="survey field; coding to verify", ai_definition="ChatGPT",
        comparison_group="within this sample only",
        verification_status="carried forward unverified; not re-attempted in this audit",
        audit_record=f"{A}/AUDIT-REPORT.md; concept-and-feasibility.md",
        access_status="public files located", redistribution_status="survey-specific terms unverified",
        uncertainty="subgroup precision and coding reliability unassessed",
        missingness_or_selection="opt-in quota sample with no verified weights; cannot support national prevalence",
        next_check="only relevant to a qualitative or mechanism study, not to a prevalence indicator",
        new_check_this_setup="false", joint_fields="unknown", design_weights_precision="no verified weights",
        evidence_level="carried-forward-unverified", id_status="existing", lead_slot="",
    ),
    dict(
        indicator_id="ANTHROPIC_CONTEXT",
        question="What does selected-user research suggest?", construct="context; patterns/experience",
        source="Anthropic linked survey / Economic Index",
        source_url="https://www.anthropic.com/research/economic-index-june-2026-report",
        sample_family="ANTHROPIC_JUNE2026_LINKED", population="Selected linked survey and usage sample",
        geography="not a geography; platform sample", fieldwork_or_reference="June 2026 report",
        unit="survey respondents and linked activity", denominator="selected sample; not a population",
        gender_measure="published respondent comparison; public linkage unavailable", ai_definition="Claude",
        comparison_group="contextual published evidence only",
        verification_status="carried forward unverified; not re-checked in this audit. Anthropic public releases do not contain the gender-linked records",
        audit_record=f"{A}/AUDIT-REPORT.md; concept-and-feasibility.md",
        access_status="gender-linked respondent data not verified public",
        redistribution_status="public release terms separate from unreleased linkage",
        uncertainty="selection; not population representation",
        missingness_or_selection="public aggregate files lack the needed user-gender linkage",
        next_check="use as attributed literature; never infer gender from occupational shares",
        new_check_this_setup="false", joint_fields="none public", design_weights_precision="not a probability sample",
        evidence_level="carried-forward-unverified", id_status="existing", lead_slot="",
    ),
    dict(
        indicator_id="RIA_AFTERACCESS_CONTEXT",
        question="How do digital access and use differ by gender in sub-Saharan Africa?",
        construct="context: digital access",
        source="Research ICT Africa, After Access gender comparative report",
        source_url="https://researchictafrica.net/research/the-state-of-gender-digital-inequality-in-sub-saharan-africa/",
        sample_family="RIA_AFTERACCESS_2022_23", population="Adults in seven sub-Saharan countries",
        geography="7 countries (list not re-verified here)", fieldwork_or_reference="2022-23 surveys",
        unit="people", denominator="varies by indicator", gender_measure="survey sex categories per the provider",
        ai_definition="none: digital access and use, not AI",
        comparison_group="context only; never a substitute for an AI measure",
        verification_status="documentation-only, carried from the coordinator log; not re-attempted here (provider page previously timed out)",
        audit_record="landscape-v1/coordination/SCOUT.md",
        access_status="provider summary and report PDF indexed", redistribution_status="unverified",
        uncertainty="not assessed", missingness_or_selection="no generative-AI use table established",
        next_check="treat as interpretive context for access gaps; do not list as an AI indicator",
        new_check_this_setup="false", joint_fields="unknown", design_weights_precision="not inspected",
        evidence_level="documentation-only", id_status="new-this-programme (coordinator-proposed)", lead_slot="4",
    ),
    dict(
        indicator_id="UK_OFCOM_ONLINE",
        question="How do UK online behaviours differ by gender?", construct="context: online use",
        source="Ofcom Online Nation",
        source_url="https://www.ofcom.org.uk/siteassets/resources/documents/research-and-data/online-research/online-nation/2024/online-nation-2024-report.pdf",
        sample_family="OFCOM_ONLINE_NATION", population="UK online adults and children",
        geography="United Kingdom (1 country)", fieldwork_or_reference="2024 edition surfaced; 2025 edition not audited",
        unit="people and measured device visits", denominator="varies by measure and panel",
        gender_measure="not audited", ai_definition="varies; distinguish survey self-reports from measured visits",
        comparison_group="not eligible until audited",
        verification_status="queued; not checked in this audit (one fetch of the Ofcom research hub returned HTTP 403)",
        audit_record="landscape-v1/coordination/SCOUT.md",
        access_status="public reports; panel data not public", redistribution_status="unverified",
        uncertainty="not assessed",
        missingness_or_selection="survey use and passively measured browser visits are different constructs",
        next_check="audit the 2025 edition and keep survey and measurement constructs separate",
        new_check_this_setup="false", joint_fields="unknown", design_weights_precision="not inspected",
        evidence_level="queued-lead", id_status="new-this-programme (coordinator-proposed)", lead_slot="5",
    ),
    dict(
        indicator_id="JP_MIC_GENAI",
        question="Who in Japan uses generative AI?", construct="participation",
        source="Japan Ministry of Internal Affairs and Communications: Information and Communications White Paper (commissioned survey) and Communications Usage Trend Survey",
        source_url="https://www.soumu.go.jp/johotsusintokei/whitepaper/ja/r07/html/nd112210.html",
        sample_family="JP_MIC_2025", population="Individuals in Japan (white paper survey) / households and members aged 6+ (Communications Usage Trend Survey)",
        geography="Japan (1 country), with US, Germany and China comparison samples in the commissioned survey",
        fieldwork_or_reference="FY2024 commissioned survey reported in the 2025 (Reiwa 7) white paper; Communications Usage Trend Survey reference point end-August",
        unit="people", denominator="survey-specific; the white-paper figure is experience of any generative-AI service",
        gender_measure="UNVERIFIED: published white-paper figures are by country and age band; a sex breakdown was not located in this dated search",
        ai_definition="generative-AI services (text, image and others)",
        comparison_group="not eligible until gender cells are verified",
        verification_status="lead, documentation-only 2026-10-01: Japanese-language search located the white-paper section reporting 26.7 per cent individual generative-AI use experience in the FY2024 survey with age breakdowns and downloadable Excel/CSV figure data; the statutory Communications Usage Trend Survey publishes e-Stat tables whose generative-AI and sex content is unverified",
        audit_record=f"{A}/search-log.csv",
        access_status="white-paper figure data and e-Stat tables are open; not yet downloaded",
        redistribution_status="unverified (Japanese government terms of use to check)",
        uncertainty="not assessed",
        missingness_or_selection="the headline figure comes from a commissioned survey, not the statutory survey; do not merge the two",
        next_check="download the white-paper figure data (datashu) and the e-Stat Communications Usage Trend Survey tables; establish whether any generative-AI item is published by sex",
        new_check_this_setup="true", joint_fields="unknown", design_weights_precision="not inspected",
        evidence_level="queued-lead", id_status="new-this-audit", lead_slot="7",
    ),
    dict(
        indicator_id="MX_ENIAG_HE",
        question="How does generative-AI use differ by sex in Mexican higher education?",
        construct="participation (higher-education population)",
        source="Mexico: ENIAG 2025 survey of generative AI in higher education (SEP-linked)",
        source_url="https://esemanal.mx/2026/05/reflexiones-sobre-la-eniag-2025-el-impacto-de-la-ia-generativa-en-la-educacion-superior/",
        sample_family="MX_ENIAG_2025",
        population="Students and teaching staff in Mexican higher education (not the general population)",
        geography="Mexico (1 country, sectoral population)",
        fieldwork_or_reference="2025; exact fieldwork dates unverified",
        unit="people", denominator="students and teachers surveyed; denominators unverified",
        gender_measure="reported by sex in secondary coverage: 69.7 per cent of men and 62.7 per cent of women using generative AI at least weekly - NOT verified against a primary document",
        ai_definition="generative AI in study and teaching",
        comparison_group="not eligible until the primary source is verified; a higher-education population is not a national population",
        verification_status="lead, SECONDARY SOURCE ONLY 2026-10-01: located through a Spanish-language search; the primary ENIAG publication was not located or read in this audit",
        audit_record=f"{A}/search-log.csv",
        access_status="primary report not located", redistribution_status="unverified",
        uncertainty="not assessed",
        missingness_or_selection="self-selected institutional survey risk; sector population only; INEGI's ENDUTIH was checked separately and no generative-AI-by-sex table was established",
        next_check="find and read the primary ENIAG 2025 publication and methodology before any use",
        new_check_this_setup="true", joint_fields="unknown", design_weights_precision="not inspected",
        evidence_level="queued-lead (secondary source)", id_status="new-this-audit", lead_slot="8",
    ),
    dict(
        indicator_id="CRANNEY_SYNTHESIS",
        question="What does existing synthesis say about gender gaps over time?",
        construct="synthesis; source-finding tool (NOT an indicator)",
        source="Cranney et al. working paper synthesis of gender gaps in generative AI",
        source_url="https://www.hbs.edu/ris/Publication%20Files/25-023_be8fb517-3dd5-40aa-97f9-4e42e1c8e6ff.pdf",
        sample_family="MULTIPLE_PRIMARY_SAMPLES",
        population="Constituent studies' populations", geography="claimed 76 sources from over 100 countries",
        fieldwork_or_reference="varies by constituent study", unit="varies", denominator="varies",
        gender_measure="varies by constituent study", ai_definition="varies by constituent study",
        comparison_group="not a harmonised dataset; never counted as independent evidence",
        verification_status="carried forward unverified; not re-checked in this audit",
        audit_record="evidence/pilot-2026-10-01/geographic-coverage.csv",
        access_status="working paper open", redistribution_status="unverified", uncertainty="varies",
        missingness_or_selection="constituent samples must be deduplicated before any country count is repeated",
        next_check="use to find primary sources; never display as an indicator or as country coverage",
        new_check_this_setup="false", joint_fields="not applicable",
        design_weights_precision="not applicable",
        evidence_level="published-finding-only", id_status="existing (pilot coverage CSV)", lead_slot="",
    ),
]

COVERAGE_FIELDS = [
    "entity", "entity_type", "region", "source_id", "construct", "genai_specific",
    "sex_gender_cells_published", "joint_sex_age_cells", "uncertainty_published",
    "status", "evidence_date", "notes",
]

EU_COUNTRIES_USE = [
    "Albania", "Austria", "Belgium", "Bosnia and Herzegovina", "Bulgaria", "Croatia",
    "Cyprus", "Czechia", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece",
    "Hungary", "Ireland", "Italy", "Kosovo", "Latvia", "Lithuania", "Luxembourg", "Malta",
    "Montenegro", "Netherlands", "North Macedonia", "Norway", "Poland", "Portugal",
    "Romania", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden", "Switzerland",
    "Türkiye",
]
# Montenegro appears only in the non-use table.
NONUSE_ONLY = {"Montenegro"}


def coverage_rows():
    rows = []
    for country in EU_COUNTRIES_USE:
        if country in NONUSE_ONLY:
            note = "present in isoc_ai_iaiuxr (non-use) only; absent from the use table"
            source = "EU_NONUSE"
        else:
            note = "present in both Eurostat tables; headline male and female cells unflagged"
            source = "EU_USE;EU_PURPOSE;EU_NONUSE"
        rows.append(dict(
            entity=country, entity_type="country/territory", region="Europe", source_id=source,
            construct="generative-AI use in the last 3 months (and purposes, non-use reasons)",
            genai_specific="yes", sex_gender_cells_published="yes (male/female)",
            joint_sex_age_cells="yes (sex x age and sex x education)", uncertainty_published="no",
            status="file-verified-published-cells", evidence_date="2026-10-01", notes=note,
        ))
    for agg in ["EU27_2020", "Euro area (EA)"]:
        rows.append(dict(
            entity=agg, entity_type="AGGREGATE (not a country)", region="Europe",
            source_id="EU_USE;EU_PURPOSE;EU_NONUSE",
            construct="generative-AI use in the last 3 months", genai_specific="yes",
            sex_gender_cells_published="yes (male/female)",
            joint_sex_age_cells="yes", uncertainty_published="no",
            status="file-verified-published-cells", evidence_date="2026-10-01",
            notes="aggregate; must never be counted as an additional country; compiled under the ESMS 60/55 per cent rule",
        ))
    rows.append(dict(
        entity="Iceland", entity_type="country/territory", region="Europe", source_id="",
        construct="generative-AI use", genai_specific="yes", sex_gender_cells_published="no",
        joint_sex_age_cells="no", uncertainty_published="no",
        status="no-source-found-in-dated-search", evidence_date="2026-10-01",
        notes="named in the Eurostat reference area but absent from both 2025 tables; no alternative national source searched",
    ))
    rows.append(dict(
        entity="United Kingdom", entity_type="country/territory", region="Europe",
        source_id="UK_DSIT_USE", construct="generative-AI user composite in the last 3 months",
        genai_specific="partly: composite includes autonomous workplace AI", sex_gender_cells_published="yes (four categories incl. 'identify in another way')",
        joint_sex_age_cells="no", uncertainty_published="no (design effect 1.67 documented; no interval in the AI workbook)",
        status="file-verified-published-cells", evidence_date="2026-10-01",
        notes="adults 16+; not comparable with the Eurostat item",
    ))
    rows.append(dict(
        entity="Brazil", entity_type="country/territory", region="Latin America and Caribbean",
        source_id="BR_CETIC_USE;BR_CETIC_PURPOSE;BR_CETIC_NONUSE",
        construct="AI-tool use in the last 3 months among internet users; purposes; non-use reasons",
        genai_specific="published under a generative-AI label; item wording says 'AI tool' with generative examples",
        sex_gender_cells_published="yes (male/female)", joint_sex_age_cells="no",
        uncertainty_published="YES (margin of error per cell)",
        status="file-verified-published-cells", evidence_date="2026-10-01",
        notes="probability sample, ages 10+, internet-user denominator; non-use reasons are multiple response",
    ))
    rows.append(dict(
        entity="Republic of Korea", entity_type="country/territory", region="Asia (East)",
        source_id="KR_NIA_USE;KR_NIA_SERVICE;KR_NIA_NONUSE",
        construct="generative-AI service experience in the last year; services used; non-use reasons",
        genai_specific="yes", sex_gender_cells_published="yes (male/female)",
        joint_sex_age_cells="YES (published sex x age)",
        uncertainty_published="no at table level (survey-level error only)",
        status="file-verified-published-cells", evidence_date="2026-10-01",
        notes="approved national statistics; internet users aged 12+; one-year window; reuse terms unresolved",
    ))
    rows.append(dict(
        entity="Canada", entity_type="country/territory", region="North America",
        source_id="CA_CSWC_WORK;CA_LFS_AI_2026",
        construct="workplace generative-AI use in the past 12 months",
        genai_specific="yes", sex_gender_cells_published="yes (Female+/Male+ in CSWC; men/women in the LFS supplement)",
        joint_sex_age_cells="no (gender x occupational exposure group in the LFS supplement)",
        uncertainty_published="CI for the adjusted odds ratio only",
        status="published-finding-only", evidence_date="2026-10-01",
        notes="two distinct samples from one provider; provinces only; crude rates equal, adjusted odds higher for Male+",
    ))
    rows.append(dict(
        entity="United States", entity_type="country/territory", region="North America",
        source_id="PEW_GENDER;PEW_GLOBAL_ATT",
        construct="chatbot ever-use and frequency; AI attitudes", genai_specific="partly (chatbots)",
        sex_gender_cells_published="yes (men/women, published report)", joint_sex_age_cells="not audited",
        uncertainty_published="margin of error in the topline",
        status="documentation-verified", evidence_date="2026-10-01",
        notes="ATP W187 shared between the US report and the global study's US February data; ever-use is not last-3-months use",
    ))
    rows.append(dict(
        entity="Australia", entity_type="country/territory", region="Oceania",
        source_id="AU_ADII_GENAI", construct="recent generative-AI use", genai_specific="yes",
        sex_gender_cells_published="not in the report; dashboard filter exists behind a terms click",
        joint_sex_age_cells="unknown", uncertainty_published="no",
        status="documentation-only", evidence_date="2026-10-01",
        notes="age, education, occupation, language, disability and remoteness breakdowns published; no gender cell obtained",
    ))
    rows.append(dict(
        entity="Japan", entity_type="country/territory", region="Asia (East)",
        source_id="JP_MIC_GENAI", construct="generative-AI use experience", genai_specific="yes",
        sex_gender_cells_published="not established in this search", joint_sex_age_cells="unknown",
        uncertainty_published="unknown", status="documentation-only", evidence_date="2026-10-01",
        notes="white-paper commissioned survey publishes country and age breakdowns; statutory survey tables unchecked",
    ))
    rows.append(dict(
        entity="Mexico", entity_type="country/territory", region="Latin America and Caribbean",
        source_id="MX_ENIAG_HE", construct="generative-AI use in higher education", genai_specific="yes",
        sex_gender_cells_published="reported in secondary coverage only", joint_sex_age_cells="unknown",
        uncertainty_published="unknown", status="documentation-only", evidence_date="2026-10-01",
        notes="ENDUTIH (national ICT survey) checked separately: no generative-AI-by-sex table established in this dated search",
    ))
    rows.append(dict(
        entity="47 countries and jurisdictions (Melbourne/KPMG study)", entity_type="multi-country study",
        region="multiple", source_id="MELB_KPMG_TRUST",
        construct="trust, attitudes, AI use at work", genai_specific="no (randomly allocated AI framings)",
        sex_gender_cells_published="NO country-by-gender outcome cells; composition only plus one global null statement",
        joint_sex_age_cells="no", uncertainty_published="no",
        status="documentation-verified", evidence_date="2026-10-01",
        notes="online panel, 1001-1098 per country; other-gender options not offered in some countries",
    ))
    rows.append(dict(
        entity="36 countries plus the United States (Pew global study)", entity_type="multi-country study",
        region="multiple", source_id="PEW_GLOBAL_ATT", construct="AI attitudes and expectations",
        genai_specific="no", sex_gender_cells_published="selected statistically significant differences only (11 countries for one item)",
        joint_sex_age_cells="no", uncertainty_published="per-country margin of error",
        status="documentation-verified", evidence_date="2026-10-01",
        notes="attitudes, not adoption; appendix detailed tables are by age, education and income",
    ))
    rows.append(dict(
        entity="7 sub-Saharan countries (RIA After Access)", entity_type="multi-country study",
        region="Africa (sub-Saharan)", source_id="RIA_AFTERACCESS_CONTEXT",
        construct="digital access and use (context)", genai_specific="no",
        sex_gender_cells_published="yes for digital access per the provider summary", joint_sex_age_cells="unknown",
        uncertainty_published="unknown", status="documentation-only", evidence_date="2026-10-01",
        notes="context only; no generative-AI use table established; carried from the coordinator log",
    ))
    rows.append(dict(
        entity="Global individual ChatGPT messages", entity_type="platform panel (not a population)",
        region="multiple", source_id="SIGNALS_TOPIC", construct="message shares by topic and name-associated gender",
        genai_specific="yes (ChatGPT)", sex_gender_cells_published="name-based proxy on messages, not people",
        joint_sex_age_cells="no", uncertainty_published="differential-privacy noise, no sampling error",
        status="blocked-access", evidence_date="2026-10-01",
        notes="three publisher URLs returned HTTP 403 to this session; publisher text obtained via the search index",
    ))
    # Regions and sub-regions with explicit not-searched / no-source-found status
    not_searched = [
        ("Caribbean (all states and territories)", "Latin America and Caribbean"),
        ("Central America excluding Mexico", "Latin America and Caribbean"),
        ("South America excluding Brazil", "Latin America and Caribbean"),
        ("Pacific island states", "Oceania"),
        ("New Zealand", "Oceania"),
        ("Central Asia", "Asia (Central)"),
        ("South Asia (India, Pakistan, Bangladesh, Sri Lanka, Nepal)", "Asia (South)"),
        ("Southeast Asia excluding Singapore", "Asia (Southeast)"),
        ("China", "Asia (East)"),
        ("Sub-Saharan Africa national statistical offices", "Africa (sub-Saharan)"),
        ("North Africa excluding Egypt and Morocco", "Africa (North)"),
        ("West Asia excluding Saudi Arabia, UAE and Qatar", "West Asia"),
        ("Russia, Belarus, Ukraine, Moldova, Caucasus", "Europe (non-EU east)"),
    ]
    for entity, region in not_searched:
        rows.append(dict(
            entity=entity, entity_type="region or country group", region=region, source_id="",
            construct="sex-disaggregated generative-AI use", genai_specific="n/a",
            sex_gender_cells_published="unknown", joint_sex_age_cells="unknown",
            uncertainty_published="unknown", status="NOT-SEARCHED", evidence_date="2026-10-01",
            notes="no targeted search performed in this bounded audit; this is not an absence finding",
        ))
    searched_none = [
        ("Singapore", "Asia (Southeast)", "coordinator search S07, English only: no individual gender-by-use table established"),
        ("Saudi Arabia", "West Asia", "coordinator search S08, English only: no table established; Arabic search open"),
        ("Egypt", "Africa (North)", "coordinator search S09, English only: no primary joint table established"),
        ("Morocco", "Africa (North)", "coordinator search S10, French query: no primary joint table established"),
        ("United Arab Emirates", "West Asia", "this audit search S29, English only: official statistical portals surfaced no individual generative-AI-by-sex indicator; Arabic search open"),
        ("Qatar", "West Asia", "this audit search S29, English only: no official indicator established; Arabic search open"),
        ("South Africa", "Africa (sub-Saharan)", "this audit search S26: no official NSO table established; non-official estimates exist with incompatible constructs (panel survey, product telemetry, OECD-Cisco poll)"),
        ("Kenya", "Africa (sub-Saharan)", "this audit search S26: no official NSO table established; non-official estimates differ by an order of magnitude because of differing populations and definitions"),
    ]
    for entity, region, note in searched_none:
        rows.append(dict(
            entity=entity, entity_type="country/territory", region=region, source_id="",
            construct="sex-disaggregated generative-AI use", genai_specific="n/a",
            sex_gender_cells_published="none found", joint_sex_age_cells="none found",
            uncertainty_published="n/a", status="no-source-found-in-dated-search",
            evidence_date="2026-10-01", notes=note,
        ))
    return rows


SEARCH_FIELDS = [
    "search_id", "retrieved", "region", "scope", "method", "query_or_url",
    "candidate_ids", "result", "limits",
]

SEARCHES = [
    ("S11", "2026-10-01", "Europe", "EU27 and EFTA/candidates", "direct provider API and metadata",
     "https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/isoc_ai_iaiu/?format=TSV&compressed=false ; .../isoc_ai_iaiuxr/ ; https://ec.europa.eu/eurostat/cache/metadata/en/isoc_i_esms.htm",
     "EU_USE;EU_PURPOSE;EU_NONUSE", "file checked; hashes identical to the pilot; 37 and 38 geo codes re-counted",
     "no standard errors in the tables or metadata; country notes not in the metadata page"),
    ("S12", "2026-10-01", "Europe", "EU legal basis", "web search after direct fetch failed",
     "Commission Implementing Regulation 2025/1322 ICT usage households individuals reference year 2026 (eur-lex.europa.eu returned HTTP 202 to three direct requests)",
     "EU_USE", "resolved: EUR-Lex titles 2025/1322 for reference year 2026; the ESMS page cites it as 2025; the 2025 act appears as draft Ares(2024)3093436",
     "EUR-Lex blocks automated fetches; title read from the search index and cross-checked against the ESMS text"),
    ("S13", "2026-10-01", "Europe", "EU country-specific notes", "direct provider (two routes)",
     "https://circabc.europa.eu/ui/group/4f80b004-7f0a-4e5a-ba91-a7bb40cc0304/library/0581a1a1-06cd-4626-89e4-b43cae2d7d8c and the CIRCABC node API",
     "EU_NONUSE", "blocked: HTTP 404 to the UI URL and to the API; C2 cause remains unresolved",
     "CIRCABC is a script-driven library; no alternative public mirror found"),
    ("S14", "2026-10-01", "Europe", "EU compilers' manual", "direct provider",
     "https://ec.europa.eu/eurostat/en/web/products-manuals-and-guidelines/w/ks-01-25-011",
     "EU_USE;EU_NONUSE", "documentation checked: the available manual covers the 2024 survey, published 24 April 2025",
     "predates the 2025 generative-AI module, so it cannot explain the C2 residual"),
    ("S15", "2026-10-01", "Europe", "United Kingdom", "direct provider (re-download and technical documents)",
     "https://www.gov.uk/government/statistics/dsit-public-engagement-survey-20252026 (+ technical report, paper questionnaire, AI tables ODS)",
     "UK_DSIT_USE", "file checked: workbook byte-identical to the coordinator vintage; design, weighting, design effect 1.67, CI method and note-1 composite documented",
     "no confidence interval in the AI workbook; no published gender-by-age cell"),
    ("S16", "2026-10-01", "Latin America and Caribbean", "Brazil", "direct provider (tables, methodology, dictionary)",
     "https://www.cetic.br/pt/tics/domicilios/2025/individuos/M1/ ; M2 ; M3 ; https://cetic.br/pt/arquivos/domicilios/2025/individuos/",
     "BR_CETIC_USE;BR_CETIC_PURPOSE;BR_CETIC_NONUSE", "file checked: proportions, totals and margins of error for sex rows; questionnaire item C13A and fieldwork March-September 2025 documented",
     "two licence statements on provider pages; respondent microdata deliberately not downloaded"),
    ("S17", "2026-10-01", "North America", "Canada (CSWC)", "direct provider",
     "https://www150.statcan.gc.ca/n1/pub/75-006-x/2026001/article/00007-eng.htm",
     "CA_CSWC_WORK", "published cells verified: crude 22/22 per cent; Male+ OR 1.15 (1.02-1.29); confidentiality aggregation note preserved",
     "no data table or microdata audited; odds ratio must not become a percentage-point gap"),
    ("S18", "2026-10-01", "North America", "Canada (LFS supplement)", "direct provider",
     "https://www150.statcan.gc.ca/n1/daily-quotidien/260730/dq260730b-eng.htm",
     "CA_LFS_AI_2026", "published cells verified: men 57.0 vs women 50.9 (HEHC) and 52.9 vs 41.2 (HELC)",
     "distinct sample from CSWC; exposure groups are a modelled occupational classification"),
    ("S19", "2026-10-01", "multiple", "Pew global study and US report", "direct provider (pages, toplines, report PDF)",
     "https://www.pewresearch.org/global/2026/09/17/... ; .../methodology-global-ai-2026/ ; .../appendix-detailed-tables-global-ai-2026/ ; https://www.pewresearch.org/internet/2026/06/17/the-gender-gap-in-ai/",
     "PEW_GLOBAL_ATT;PEW_GENDER", "documentation verified: 42151 across 36 countries, 8 Feb-13 May 2026; US W187 and W195; appendix tables by age/education/income, gender only as significant differences",
     "no country-by-gender matrix published; microdata need an account, not attempted"),
    ("S20", "2026-10-01", "Asia (East)", "Republic of Korea", "direct provider file endpoint with referer",
     "https://www.nia.or.kr/site/nia_kor/ex/bbs/View.do?bcIdx=29580&cbIdx=99870 -> /common/board/Download.do?...fileNo=1|2",
     "KR_NIA_USE;KR_NIA_SERVICE;KR_NIA_NONUSE", "file checked: English statistical tables and report acquired; generative-AI tables with Gender and Gender*Age blocks extracted",
     "reuse terms unresolved (NIA copyright statement); table 134 not extracted"),
    ("S21", "2026-10-01", "Oceania", "Australia", "direct provider (report and dashboard)",
     "https://digitalinclusionindex.org.au/wp-content/uploads/2025/10/ADII-Report-2025_V6-Remediated.pdf ; https://dashboard.digitalinclusionindex.org.au/GenerativeAI.aspx",
     "AU_ADII_GENAI", "documentation checked: report has no gender cell for generative AI; dashboard gated behind a terms-acceptance click that was not accepted",
     "accepting provider terms is outside this assignment; index site page returned 404"),
    ("S22", "2026-10-01", "multiple", "OpenAI Signals", "direct provider (three URLs) then search index",
     "https://openai.com/signals/ ; /signals/data-download/ ; /signals/data/ (all HTTP 403); search query 'OpenAI Signals data download current release version 2026 licence'",
     "SIGNALS_TOPIC", "blocked for download; publisher text shows citation still 'OpenAI Signals v2.0', README v1.1, CC BY 4.0, July 2024-June 2026, name-based gender proxy",
     "no file verification possible; search-index text is weaker evidence than a retrieved page"),
    ("S23", "2026-10-01", "multiple", "ILO exposure index", "direct provider (two routes)",
     "https://www.ilo.org/publications/generative-ai-and-jobs-refined-global-index-occupational-exposure ; https://ilostat.ilo.org/topics/artificial-intelligence/ (HTTP 403)",
     "ILO_EXPOSURE", "documentation only: method verified; no country-year series linked from the publication page",
     "series still not located; exposure is not adoption and sex enters only as occupational composition"),
    ("S24", "2026-10-01", "Asia (East)", "Japan", "web search in Japanese (two queries)",
     "'通信利用動向調査 2025 生成AI 利用率 男女別' and '総務省 通信利用動向調査 令和6年 生成AI 利用 個人 性別 統計表'",
     "JP_MIC_GENAI", "new lead: MIC white paper reports 26.7 per cent individual generative-AI use (FY2024 survey) with age breakdowns and downloadable figure data; statutory survey tables on e-Stat unchecked",
     "no sex breakdown located; commercial panel trackers (NRC, INTAGE) report sex differences but are not official statistics"),
    ("S25", "2026-10-01", "Latin America and Caribbean", "Mexico", "web search in Spanish",
     "'INEGI ENDUTIH 2025 inteligencia artificial generativa uso por sexo'",
     "MX_ENIAG_HE", "ENDUTIH: no generative-AI-by-sex table established; separate lead found: ENIAG 2025 higher-education survey reporting 69.7 per cent of men and 62.7 per cent of women using weekly (secondary coverage)",
     "primary ENIAG document not located; higher-education population is not a national population"),
    ("S26", "2026-10-01", "Africa (sub-Saharan)", "South Africa and Kenya", "web search in English",
     "'Statistics South Africa OR Kenya official survey \"generative AI\" use by sex household 2025'",
     "", "no official national statistical table established; non-official estimates found with incompatible constructs: GWI/DataReportal online-adult panel, Microsoft product telemetry for ages 15-64, OECD-Cisco Digital Well-being poll (about 1000 per country, 14 countries incl. Brazil, South Africa, India, Mexico)",
     "English only; NSO site searches not exhausted; none of the non-official sources was audited and none is counted as a lead within the eight-lead cap"),
    ("S27", "2026-10-01", "Europe", "EWCS 2024 access", "direct provider and repository",
     "https://www.eurofound.europa.eu/en/surveys-and-data/surveys/european-working-conditions-survey/ewcs-2024 (HTTP 429) ; https://beta.ukdataservice.ac.uk/datacatalogue/studies/study?id=9353",
     "EWCS_WORK", "blocked this pass: provider rate-limited twice; catalogue page returned a script-only shell",
     "access is gated by an end-user licence in any case; no data request was made"),
    ("S28", "2026-10-01", "multiple", "ISSP 2024 release ZA10020", "archive study page",
     "https://search.gesis.org/research_data/ZA10020 (HTTP 403)",
     "ISSP_ATTITUDES", "blocked: fourth consecutive 403 across sessions; release country list still unknown",
     "programme membership is not module participation; no alternative public country list found"),
    ("S29", "2026-10-01", "West Asia and North Africa", "UAE and Qatar", "web search in English",
     "'UAE Federal Competitiveness and Statistics Centre OR Qatar Planning Statistics Authority ICT household survey 2025 artificial intelligence individuals by sex'",
     "", "no suitable official table established in this search; statistical-portal results were institutional pages and non-official population statistics",
     "English only; Arabic-language search and direct portal catalogue browsing remain open; this is not an absence finding"),
]

PERMITTED_FIELDS = [
    "cell_id", "source_id", "provider", "exact_cell_reference", "measure_definition",
    "denominator", "period", "gender_category", "published_value", "published_uncertainty",
    "verification", "reuse_condition", "display_rule",
]

PERMITTED = [
    ("C01", "EU_USE", "Eurostat", "isoc_ai_iaiu: indic_is=I_IUAI, unit=PC_IND, ind_type=M_Y16_74, geo=EU27_2020",
     "used generative AI in the last 3 months", "all individuals aged 16-74", "2025", "male (survey sex)",
     "34.91", "none published", "file-verified 2026-10-01 (hash matches pilot and manuscript snapshot)",
     "attribute Eurostat, cite DOI 10.2908/ISOC_AI_IAIU and access date, disclose modification",
     "show with the PC_IND denominator note that internet non-users count as non-adopters"),
    ("C02", "EU_USE", "Eurostat", "isoc_ai_iaiu: I_IUAI, PC_IND, F_Y16_74, EU27_2020",
     "used generative AI in the last 3 months", "all individuals aged 16-74", "2025", "female (survey sex)",
     "30.45", "none published", "file-verified 2026-10-01", "as C01", "as C01"),
    ("C03", "EU_USE", "Eurostat", "isoc_ai_iaiu: I_IUAI, PC_IND_IU3, M_Y16_74, EU27_2020",
     "used generative AI in the last 3 months", "recent internet users aged 16-74", "2025", "male",
     "37.20", "none published", "file-verified 2026-10-01", "as C01",
     "display beside C01 or state which denominator was chosen"),
    ("C04", "EU_USE", "Eurostat", "isoc_ai_iaiu: I_IUAI, PC_IND_IU3, F_Y16_74, EU27_2020",
     "used generative AI in the last 3 months", "recent internet users aged 16-74", "2025", "female",
     "32.49", "none published", "file-verified 2026-10-01", "as C01", "as C03"),
    ("C05", "EU_USE", "Eurostat", "isoc_ai_iaiu: I_IUAI, PC_IND or PC_IND_IU3, M_Y16_74 and F_Y16_74, all 35 countries plus EU27_2020 and EA",
     "used generative AI in the last 3 months", "stated unit code", "2025", "male and female",
     "see the dataset (all 74 headline cells present and unflagged)", "none published",
     "file-verified 2026-10-01 by the pilot and re-counted here",
     "as C01; check the commercial-reuse exclusion for non-EU/EFTA/candidate geographies before any commercial product",
     "aggregates must be labelled as aggregates; preserve the geographies where the female rate is higher; surface u flags in finer cells"),
    ("C06", "UK_DSIT_USE", "DSIT (Verian)", "AI tables ODS, Table_E5 rows 38-41, columns C and E-F",
     "generative AI user: used text/speech, image/video/music or autonomous workplace AI in the last 3 months",
     "all UK adults aged 16+", "fieldwork Nov 2025-Mar 2026", "Male / Female / Identify in another way / Prefer not to say",
     "63.2 (n=13,902) / 55.5 (n=15,953) / 49.2 (n=99) / 45.0 (n=671)",
     "no interval published; design effect 1.67 documented",
     "file-verified 2026-10-01 (workbook SHA-256 a34ed705...610a; coordinator extractor reproduces)",
     "Open Government Licence v3.0 except where otherwise stated; attribute DSIT",
     "print the note-1 composite definition; keep the provider's category labels; show the third category's base"),
    ("C07", "BR_CETIC_USE", "Cetic.br / NIC.br", "individuals proportion workbook, sheet M1, SEX rows, column 'Yes'",
     "used an AI tool (ChatGPT, Copilot, Gemini, Meta AI in WhatsApp) in the last 3 months",
     "internet users aged 10+", "fieldwork Mar-Sep 2025", "Masculino / Feminino",
     "34.79 / 30.49", "+/- 3.29 pp and +/- 2.78 pp (95 per cent, provider margin-of-error table)",
     "file-verified 2026-10-01 (bundle SHA-256 9ca6638c...dd930; check_cetic.py)",
     "CC BY 4.0 per the file-level dataset entry; attribute NIC.br (2025) as printed",
     "state the internet-user denominator, the age floor of 10 and the item's AI-tool wording"),
    ("C08", "BR_CETIC_NONUSE", "Cetic.br / NIC.br", "individuals proportion workbook, sheet M3, SEX rows",
     "declared reasons for not using generative AI (MULTIPLE RESPONSE)",
     "internet users aged 10+ who did not use generative AI", "fieldwork Mar-Sep 2025", "Masculino / Feminino",
     "interest/need 73.96 / 77.52; awareness 50.41 / 53.22; skills 55.00 / 60.47; security 58.65 / 67.50",
     "margin of error published per cell", "file-verified 2026-10-01", "as C07",
     "label as multiple response; never place beside Eurostat's single main reason as if comparable"),
    ("C09", "KR_NIA_USE", "MSIT / NIA", "2025 statistical tables, printed table 105, Gender rows",
     "experienced a generative-AI service within the last year", "internet users aged 12+",
     "reference date 1 Jul 2025; fieldwork Oct-Dec 2025", "Male / Female", "48.7 / 40.3",
     "no table-level error published", "file-verified 2026-10-01 (PDF SHA-256 12ec5ffe...8bc00; check_korea.py)",
     "UNRESOLVED: NIA asserts report copyright; quote with attribution, resolve terms before republishing the table",
     "state the one-year window and the internet-user base; do not rank against three-month measures"),
    ("C10", "KR_NIA_USE", "MSIT / NIA", "printed table 105, Gender*Age block",
     "experienced a generative-AI service within the last year, by sex and age band",
     "internet users aged 12+", "as C09", "Male and Female x 12-19, 20s, 30s, 40s, 50s, 60s, 70+",
     "for example male 20s 76.5 and female 20s 73.9; male 50s 38.8 and female 50s 28.4",
     "no table-level error published", "file-verified 2026-10-01", "as C09",
     "the only audited published sex-by-age generative-AI cells; display as a Korea panel only"),
    ("C11", "CA_CSWC_WORK", "Statistics Canada", "article 75-006-X 2026001/00007, text and Appendix Table A.1",
     "used generative AI at work in the previous 12 months; plus an adjusted logistic model",
     "workers aged 15-69 in the provinces", "Sep 2024-Jul 2025 averaged", "Female+ / Male+",
     "crude 22 per cent and 22 per cent; adjusted Male+ odds ratio 1.15", "95 per cent CI 1.02-1.29 for the odds ratio",
     "published-finding verified 2026-10-01", "Statistics Canada Open Licence (text not re-read)",
     "always show crude and adjusted together with the confidentiality-aggregation note; never convert the odds ratio"),
    ("C12", "CA_LFS_AI_2026", "Statistics Canada", "The Daily, 30 July 2026, text",
     "used generative AI at work in the past 12 months, within occupational exposure groups",
     "workers aged 15-69 in the provinces", "March 2026", "men / women",
     "HEHC 57.0 / 50.9; HELC 52.9 / 41.2", "none published",
     "published-finding verified 2026-10-01", "as C11",
     "label the exposure grouping as modelled and occupational; keep separate from the CSWC cells"),
    ("C13", "PEW_GLOBAL_ATT", "Pew Research Center", "report text and gender chart, 17 September 2026",
     "expects AI to lead to fewer jobs", "adults per country", "8 Feb-13 May 2026 (US Feb and Jun 2026 waves)",
     "men / women", "women more likely than men in 11 mostly high-income countries; France difference 10 pp",
     "per-country margin of error in the topline; no gender-cell error",
     "documentation-verified 2026-10-01", "quote with attribution; microdata not accessed",
     "attitudes only; never shown as adoption; state that only significant differences are published"),
    ("C14", "PEW_GENDER", "Pew Research Center", "Americans and AI 2026, gender section",
     "chatbot use and related attitudes among US adults", "US adults", "ATP W187, 17-23 Feb 2026",
     "men / women", "see the report's published gender figures", "topline margin of error",
     "documentation-verified 2026-10-01", "quote with attribution",
     "ever-use is not last-3-months use; disclose the shared wave with C13's US data"),
    ("C15", "MELB_KPMG_TRUST", "University of Melbourne and KPMG",
     "Trust, attitudes and use of AI 2025, workplace section", "gender differences in AI use and attitudes at work",
     "employee respondents across 47 countries", "Nov 2024-mid-Jan 2025", "women / men / other reported genders",
     "published global statement: no gender differences in AI use or attitudes toward AI at work",
     "none published", "documentation-verified 2026-10-01", "CC BY-NC-SA 4.0, non-commercial only",
     "quote as a global null for broad AI at work; state the online-panel design and that some countries omitted other-gender options"),
]


def write(name, fields, rows):
    path = OUT / name
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fields, lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow(row)
    print(f"wrote {path} ({len(rows)} rows)")


def main():
    write("source-register.csv", REGISTER_FIELDS, REGISTER)
    write("coverage.csv", COVERAGE_FIELDS, coverage_rows())
    write("search-log.csv", SEARCH_FIELDS,
          [dict(zip(SEARCH_FIELDS, s)) for s in SEARCHES])
    write("permitted-cells.csv", PERMITTED_FIELDS,
          [dict(zip(PERMITTED_FIELDS, p)) for p in PERMITTED])


if __name__ == "__main__":
    main()
